import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${roboto.className} font-sans`}
      >
        <header>
          <h1 className="title">Treina <span className="titleSecondWord">Blog</span></h1>
        </header>
        {children}
      </body>
    </html>
  );
}
